[build]
  # Publish directory (where your static files are)
  publish = "."
  
  # Build command (if you have any build process)
  command = ""

[build.environment]
  # Node version (if needed)
  NODE_VERSION = "18"

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Simple redirect for SPA (removed problematic conditions)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
